### ISSUE TITLE
Add a python code to implement sieve of eratosthenes

### ISSUE THREAD

**Issue by sachin-duhan26** [neophytz/hacktoberfest_2022#5]

**Comment by piyush-sri** [comment]
i would like to work on this issue

**Comment by sachin-duhan26** [comment]
@piyush-sri make sure that you create a ```folder``` in root directory with ```<programming_language>``` name, eg. ```python``` and then add your file into it.

**Comment by piyush-sri** [comment]
I opened a pull request by adding the python folder and sieveofErastosthenes file .Please have a look.

**Comment by Shobhan-Pakhira** [comment]
@sachin-duhan26 I would like to add an alternative to this issue
